# themes from https://github.com/alacritty/alacritty-theme

import = [
    "~/.config/alacritty/themes/catppuccin-frappe.toml"
]

[env]
TERM = "xterm-256color"

[font]
size = 15

[font.normal]
family = "Hack Nerd Font Mono"

[window.padding]
x = 7
y = 0
