# themes from https://github.com/alacritty/alacritty-theme

import = [
    "~/.config/alacritty/themes/tokyonight_storm.toml"
]

[env]
TERM = "xterm-256color"
ALACRITTY = "true"

[font]
size = 13

[font.normal]
family = "Hack Nerd Font Mono"

[window.padding]
x = 7
y = 0
